stages:
  - build
  - archive
 
build_project:
  stage: build
  script:
    - xcodebuild clean -workspace CIHub-Lab.xcworkspace -scheme CIHub-Lab | xcpretty
    - xcodebuild test -workspace CIHub-Lab.xcworkspace -scheme CIHub-Lab -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' | xcpretty -s
    - swiftlint
  only:
    - development
  tags:
    - Server32820
    
archive_project:
  stage: archive
  script:
    - xcodebuild clean -workspace CIHub-Lab.xcworkspace -scheme CIHub-Lab | xcpretty
    - xcodebuild test -workspace CIHub-Lab.xcworkspace -scheme CIHub-Lab -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' | xcpretty -s
    - fastlane beta
  only:
    - archive_fabric
  tags:
    - Server32820
