disabled_rules: # rule identifiers to exclude from running
  - colon
#  - comma
#  - control_statement
#  - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
  - line_length
  - nesting
#  - opening_brace
#  - operator_whitespace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
  - trailing_whitespace
#  - type_body_length
#  - type_name
#  - variable_name_max_length
#  - variable_name_min_length
#  - variable_name
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  - CISetUp
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
colon:
    flexible_right_spacing: true
file_length:
  - 1000
function_body_length:
  - 120
  - 180
type_body_length:
  - 500 # Warning
  - 600 # Error
warning_threshold: 100
